# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

Vagrant.configure(2) do |config|

  config.vm.box = "debian/bullseye64"
  config.vm.box_download_insecure = true
  config.disksize.size = '80GB'

  config.vm.provider "virtualbox" do |vb|
     vb.customize ['modifyvm', :id, "--memory", "16416"]
     vb.customize ['modifyvm', :id, "--cpus", "4"]
     vb.customize ['modifyvm', :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
     vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
     vb.customize ["modifyvm", :id, "--vram", "128"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
     vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
     vb.customize ["modifyvm", :id, "--name", "debian11-win"]
     # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end
  
  config.vm.network "private_network", ip: "192.168.51.103"
  config.vm.network "forwarded_port", guest: 8080, host: 38080
  config.vm.network "forwarded_port", guest: 8081, host: 38081
  config.vm.network "forwarded_port", guest: 8082, host: 38082
  config.vm.network "forwarded_port", guest: 8083, host: 38083
  config.vm.network "forwarded_port", guest: 8084, host: 38084
  config.vm.network "forwarded_port", guest: 8085, host: 38085
  
  config.vm.synced_folder "/Users/Benjamin/Documents/project/", "/home/vagrant/Documents/",
    automount: true

  config.vm.provision 'shell', path: '../scripts/debian11.sh'

end
