# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

# For China only
@aliSource = <<SCRIPT
sed -i 's/archive.ubuntu.com/mirrors.aliyun.com/g' /etc/apt/sources.list
SCRIPT

@zsh = <<SCRIPT
apt-get update
apt-get install -y zsh git
git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /home/vagrant/.oh-my-zsh
sudo chsh -s $(grep /zsh$ /etc/shells | tail -1) vagrant
SCRIPT

@docker = <<SCRIPT
curl -sSL https://get.docker.com/ | sh
usermod -aG docker vagrant
SCRIPT

@shipyard = <<SCRIPT
curl -s https://shipyard-project.com/deploy | bash -s
SCRIPT

@vimrc = <<SCRIPT
docker pull benjah1/vimrc
SCRIPT

@tmux = <<SCRIPT
apt-get update
apt-get install -y tmux
SCRIPT

@symlink = <<SCRIPT
ln -s /vagrant/.zshrc /home/vagrant/.zshrc
ln -s /vagrant/.tmux.conf /home/vagrant/.tmux.conf
SCRIPT

@cleanup = <<SCRIPT
echo "dd if=/dev/zero of=/bigemptyfile bs=4096k" > /home/vagrant/cleanup.sh
echo "rm -rf /bigemptyfile" >> /home/vagrant/cleanup.sh
chmod +x /home/vagrant/cleanup.sh
SCRIPT

@youtube = <<SCRIPT
mkdir /usr/local/bin -p
curl https://yt-dl.org/latest/youtube-dl -o /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure = true
  config.disksize.size = '80GB'

  config.vm.provider "virtualbox" do |vb|
     vb.customize ['modifyvm', :id, "--memory", "6144"]
     vb.customize ['modifyvm', :id, "--cpus", "8"]
     vb.customize ['modifyvm', :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--name", "dockerdev"]
  end
  
  config.vm.network "private_network", ip: "192.168.51.103"
  config.vm.network "forwarded_port", guest: 8080, host: 38080
  config.vm.network "forwarded_port", guest: 8081, host: 38081
  config.vm.network "forwarded_port", guest: 8082, host: 38082
  config.vm.network "forwarded_port", guest: 8083, host: 38083
  config.vm.network "forwarded_port", guest: 8084, host: 38084
  config.vm.network "forwarded_port", guest: 8085, host: 38085
  
  config.vm.synced_folder "/Users/ben.huang/", "/home/vagrant/default/", :type => "nfs",
     mount_options: ['nolock,vers=3,udp,noatime,actimeo=1']

  #config.ca_certificates.enabled = true
  #config.ca_certificates.certs = [
  #  '/usr/local/etc/openssl/cert.pem'
  #]

  # config.vm.provision 'shell', inline: @aliSource
  config.vm.provision 'shell', inline: @zsh
  config.vm.provision 'shell', inline: @docker
  # config.vm.provision 'shell', inline: @shipyard
  # config.vm.provision 'shell', inline: @vimrc
  config.vm.provision 'shell', inline: @tmux
  # config.vm.provision 'shell', inline: @symlink
  # config.vm.provision 'shell', inline: @cleanup
  # config.vm.provision 'shell', inline: @youtube

end
