# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

@zsh = <<SCRIPT
git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /home/vagrant/.oh-my-zsh
apt-get update
apt-get install -y zsh git
sudo chsh -s $(grep /zsh$ /etc/shells | tail -1) vagrant
chmod 777 /home/vagrant/.oh-my-zsh/cache
SCRIPT

@docker = <<SCRIPT
curl -sSL https://get.docker.com/ | sh
usermod -aG docker vagrant
SCRIPT

@kubernetes = <<SCRIPT
mkdir /usr/local/bin -p
curl -sSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-amd64
chmod +x /usr/local/bin/kind
curl -sSLo /usr/local/bin/kubectl https://storage.googleapis.com/kubernetes-release/release/`curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt`/bin/linux/amd64/kubectl
chmod +x /usr/local/bin/kubectl
SCRIPT

@tmux = <<SCRIPT
apt-get update
apt-get install -y tmux
SCRIPT

@devtool = <<SCRIPT
apt-get update
apt-get install -y jq
SCRIPT

@symlink = <<SCRIPT
ln -s /home/vagrant/default/Documents /home/vagrant/Documents
ln -s /home/vagrant/Documents/dotfiles/dotfiles/.tmux.conf /home/vagrant/.tmux.conf
ln -s /home/vagrant/Documents/dotfiles/dotfiles/.zshrc /home/vagrant/.zshrc
SCRIPT

@cleanup = <<SCRIPT
echo "dd if=/dev/zero of=/bigemptyfile bs=4096k" > /home/vagrant/cleanup.sh
echo "rm -rf /bigemptyfile" >> /home/vagrant/cleanup.sh
chmod +x /home/vagrant/cleanup.sh
SCRIPT

@youtube = <<SCRIPT
mkdir /usr/local/bin -p
curl https://yt-dl.org/latest/youtube-dl -o /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl
SCRIPT

@ssh_pub = <<SCRIPT
# laptop cygwin
echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDJOt2eCC7Azy/YKfabVuBDG2UOt+uU2zZgA7lMYobTYvs+5z61kDQZHypGwC7cHq4JY8xbovMkq7LbQSOPtkmOaT6LxHIWA4MRALTd5UGxFmoPX2L2twjSbsXCgbb9Q4M5oarVbanwrxAlws+SwnrGQQQNab1/FEHzTi2UhgeRnWiHy0nAP21bxcun5NBCUCj+CgqUTV2iA/dpn3gJExsbuE+VzyWGJquoZLGG5o0JFOmDVlw/OB6eNGjUOK2t6GErQG0cBPMLTw2JV8TmSrC4SVsqBadpwpli7Q82KZxflrAhRvS7JdndSwR5HU0QrkVYPMz14O1GMggdj6tq5rrpP99TWs5mXWXHeKgvBCpiNKdqW78Ft+sNoFKE38CkxUIsjMLVwVb8Xsb/jORK+Te75NRvmH6gkE+wDJ9asK2RVXzHnEXXJ9i7MYEc8Em5rfnfeXIxQDxnO8TD/d+e+CtN3mJIFOHlFyflNJdmK0YSDdPTcP5BkRyQQfvCdnFHbEM= Benjamin@benjamin-pc" >> /home/vagrant/.ssh/authorized_keys
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure = true
  config.disksize.size = '35GB'

  config.vm.provider "virtualbox" do |vb|
     vb.customize ['modifyvm', :id, "--memory", "30720"]
     vb.customize ['modifyvm', :id, "--cpus", "20"]
     # vb.customize ['modifyvm', :id, "--natdnshostresolver1", "on"]
     # vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]

     # vb.customize ["modifyvm", :id, "--nic2", "bridged"]
     # vb.customize ["modifyvm", :id, "--bridgeadapter2", "wlx28107b4429f3"]
     vb.customize ["modifyvm", :id, "--name", "1804-ram"]
     vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
     vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
     vb.customize ["modifyvm", :id, "--vram", "128"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
     vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
  end
  
  # config.vm.network "private_network", ip: "192.168.51.103"
  config.vm.network :public_network, :bridge => "eno1", ip: "192.168.0.49"

  # config.vm.network "public_network", :bridge => 'wlx28107b4429f3'
  config.vm.network "forwarded_port", guest: 8080, host: 38080
  config.vm.network "forwarded_port", guest: 8081, host: 38081
  config.vm.network "forwarded_port", guest: 8082, host: 38082
  config.vm.network "forwarded_port", guest: 8083, host: 38083
  config.vm.network "forwarded_port", guest: 8084, host: 38084
  config.vm.network "forwarded_port", guest: 8085, host: 38085
  
  config.vm.synced_folder "/home/benjah1/", "/home/vagrant/default/",
     create: true, 
     mount_options: ['dmode=755', 'fmode=764']

  config.vm.provision 'shell', inline: @symlink
  config.vm.provision 'shell', inline: @zsh
  config.vm.provision 'shell', inline: @docker
  config.vm.provision 'shell', inline: @kubernetes
  config.vm.provision 'shell', inline: @tmux
  config.vm.provision 'shell', inline: @devtool
  config.vm.provision 'shell', inline: @zsh
  config.vm.provision 'shell', inline: @docker
  config.vm.provision 'shell', inline: @tmux
  # config.vm.provision 'shell', inline: @cleanup
  # config.vm.provision 'shell', inline: @youtube

end
