# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.

@zsh = <<SCRIPT
apt-get update
apt-get install -y zsh git
git clone --depth=1 https://github.com/robbyrussell/oh-my-zsh.git /home/vagrant/.oh-my-zsh
sudo chsh -s $(grep /zsh$ /etc/shells | tail -1) vagrant
SCRIPT

@docker = <<SCRIPT
curl -sSL https://get.docker.com/ | sh
usermod -aG docker vagrant
SCRIPT

@kind = <<SCRIPT
mkdir /usr/local/bin -p
curl -sSLo /usr/local/bin/kind https://github.com/kubernetes-sigs/kind/releases/download/v0.8.1/kind-linux-amd64
chmod +x /usr/local/bin/kind
SCRIPT

@tmux = <<SCRIPT
apt-get update
apt-get install -y tmux
SCRIPT

@symlink = <<SCRIPT
ln -s /home/vagrant/Documents/dotfiles/dotfiles/.tmux.conf /home/vagrant/.tmux.conf
ln -s /home/vagrant/Documents/dotfiles/dotfiles/.zshrc /home/vagrant/.zshrc
SCRIPT

@cleanup = <<SCRIPT
echo "dd if=/dev/zero of=/bigemptyfile bs=4096k" > /home/vagrant/cleanup.sh
echo "rm -rf /bigemptyfile" >> /home/vagrant/cleanup.sh
chmod +x /home/vagrant/cleanup.sh
SCRIPT

@youtube = <<SCRIPT
mkdir /usr/local/bin -p
curl https://yt-dl.org/latest/youtube-dl -o /usr/local/bin/youtube-dl
chmod a+rx /usr/local/bin/youtube-dl
SCRIPT

Vagrant.configure(2) do |config|

  config.vm.box = "ubuntu/bionic64"
  config.vm.box_download_insecure = true
  config.disksize.size = '80GB'

  config.vm.provider "virtualbox" do |vb|
     vb.customize ['modifyvm', :id, "--memory", "10240"]
     vb.customize ['modifyvm', :id, "--cpus", "4"]
     vb.customize ['modifyvm', :id, "--natdnshostresolver1", "on"]
     vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
     vb.customize ["modifyvm", :id, "--name", "1804-win"]
     vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
     vb.customize ["modifyvm", :id, "--graphicscontroller", "vmsvga"]
     vb.customize ["modifyvm", :id, "--vram", "128"]
     vb.customize ["modifyvm", :id, "--accelerate3d", "on"]
     vb.customize ["modifyvm", :id, "--accelerate2dvideo", "on"]
     # vb.customize ["modifyvm", :id, "--hwvirtex", "on"]
  end
  
  config.vm.network "private_network", ip: "192.168.51.103"
  config.vm.network "forwarded_port", guest: 8080, host: 38080
  config.vm.network "forwarded_port", guest: 8081, host: 38081
  config.vm.network "forwarded_port", guest: 8082, host: 38082
  config.vm.network "forwarded_port", guest: 8083, host: 38083
  config.vm.network "forwarded_port", guest: 8084, host: 38084
  config.vm.network "forwarded_port", guest: 8085, host: 38085
  
  config.vm.synced_folder "/Users/Benjamin/Documents/project/", "/home/vagrant/Documents/", :type => "nfs",
     mount_options: ['nolock,vers=3,udp,noatime,actimeo=1']

  config.vm.provision 'shell', inline: @symlink
  config.vm.provision 'shell', inline: @zsh
  config.vm.provision 'shell', inline: @docker
  config.vm.provision 'shell', inline: @kind
  config.vm.provision 'shell', inline: @tmux
  # config.vm.provision 'shell', inline: @cleanup
  # config.vm.provision 'shell', inline: @youtube

end
